#ifndef INTERRUPTS_CONFIG_H
#define INTERRUPTS_CONFIG_H

#define ISR_MIN_PRIORITY 15

/* Configuration for EXTI interrupt priorities */

#define EXTI0_ISR_PRIORITY (ISR_MIN_PRIORITY)
#define EXTI1_ISR_PRIORITY (ISR_MIN_PRIORITY)
#define EXTI2_ISR_PRIORITY (ISR_MIN_PRIORITY)
#define EXTI3_ISR_PRIORITY (ISR_MIN_PRIORITY)
#define EXTI4_ISR_PRIORITY (ISR_MIN_PRIORITY)
#define EXTI9_5_ISR_PRIORITY (ISR_MIN_PRIORITY)
#define EXTI15_10_ISR_PRIORITY (ISR_MIN_PRIORITY)


/* Configuration for TIM interrupt priorities */

#define TIM1_ISR_PRIORITY (ISR_MIN_PRIORITY)
#define TIM2_ISR_PRIORITY (ISR_MIN_PRIORITY - 1)
#define TIM3_ISR_PRIORITY (ISR_MIN_PRIORITY)
#define TIM6_ISR_PRIORITY (ISR_MIN_PRIORITY)
#define TIM7_ISR_PRIORITY (ISR_MIN_PRIORITY)
#define TIM15_ISR_PRIORITY (ISR_MIN_PRIORITY)
#define TIM16_ISR_PRIORITY (ISR_MIN_PRIORITY)

#endif // INTERRUPTS_CONFIG_H