#ifndef TASK_SCHEDULER_1_ID_CONFIG_H
#define TASK_SCHEDULER_1_ID_CONFIG_H

enum taskSchedulerId {
    TS_ID_READ_AL_SENSOR_1,
    TS_ID_READ_AL_SENSOR_2,
    TS_ID_BUTTON_UP_PROCESS_ISR,
    TS_ID_BUTTON_UP_SINGLE_CLICK,
    TS_ID_BUTTON_UP_PRESS_AND_HOLD,
    TS_ID_BUTTON_DOWN_PROCESS_ISR,
    TS_ID_BUTTON_DOWN_SINGLE_CLICK,
    TS_ID_BUTTON_DOWN_PRESS_AND_HOLD
};

/* Configure Repeate Recipe ID*/

#endif // TASK_SCHEDULER_1_ID_CONFIG_H